FROM harbor.sourcefind.cn:5443/dcu/admin/base/pytorch:2.5.1-ubuntu22.04-dtk25.04.2-py3.10-minimal

ENV PYTHONUNBUFFERED=1 \
    DEBIAN_FRONTEND=noninteractive \
    TZ=Asia/Shanghai \
    PIP_DISABLE_PIP_VERSION_CHECK=1 \
    PIP_ROOT_USER_ACTION=ignore

# # 更新系统包并安装常用工具
# RUN apt-get update && \
#     apt-get install -y --no-install-recommends \
#         apt-utils \
#         curl \
#         wget \
#         git \
#         vim && \
#     apt-get clean && \
#     rm -rf /var/lib/apt/lists/*

# 设置工作目录（保留原有）
WORKDIR /workspace/ms-swift

# 设置 pip 镜像源并升级基础工具（保留原有）
RUN pip config set global.index-url https://mirrors.aliyun.com/pypi/simple/ && \
    pip install --upgrade pip "setuptools<81" wheel

# 复制项目代码
COPY . /workspace/ms-swift/

# 安装 ms-swift 依赖
RUN pip install -e '.[all]' && \
    rm -rf /root/.cache/pip /tmp/* /var/tmp/*

# 暴露端口
ENV WEBUI_PORT=8000
EXPOSE 8000

# Copy aicp-init script
RUN mkdir -p /aicp-init/script
COPY aicp-init /aicp-init/script/aicp-init
RUN chmod +x /aicp-init/script/aicp-init

# 启动命令
ENTRYPOINT [ "swift", "web-ui" ]